In [ ]:
print("hello")

hello


In [ ]:
import pandas as pd


In [ ]:
file = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
lemon = pd.read_csv(file)
print(lemon);

   온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48
5  25   50


In [ ]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(파일경로)
 
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(파일경로)

In [ ]:
print(iris.shape)

(150, 5)


In [ ]:
print(lemon.shape)

(6, 2)


In [ ]:
print(lemon.columns)

Index(['온도', '판매량'], dtype='object')


In [ ]:
print(lemon.columns)
print(boston.columns)
print(iris.columns)

Index(['온도', '판매량'], dtype='object')
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [ ]:
index = lemon[['온도']]
index2 = lemon[['판매량']]
print(index.shape, index2.shape)

index = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
index2 = boston[['medv']]
print(index.shape, index2.shape)

index = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
index2 = iris[['품종']]
print(index.shape, index2.shape)

(6, 1) (6, 1)
(506, 13) (506, 1)
(150, 4) (150, 1)


In [ ]:
boston.head()

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [ ]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
# 데이터 준비
file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
file_data = pd.read_csv(file_path)
file_data.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [ ]:
# 종속, 독립변수
inV = file_data[['온도']]
deV = file_data[['판매량']]
print(inV.shape, deV.shape)

(6, 1) (6, 1)


In [ ]:
# 모델 만들기
X = tf.keras.layers.Input(shape=[1])    #독립변수의 수 1개니까 shape=[1]
Y = tf.keras.layers.Dense(1)(X)          #종속변수 1개 니까
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')               #모델이 학습 할 방법


In [ ]:
# 모델 학습 시키기
model.fit(inV,deV,epochs=10000,verbose=0) # 가져온 데이터 넣기, verbose=0은 학습상황 안보여줌

In [ ]:
# 만번 학습 확인해보기 loss값
model.fit(inV,deV,epochs=10) # 가져온 데이터 넣기

Epoch 1/10
1/1 [==============================] - 0s 2ms/step - loss: 2.0125e-04
Epoch 2/10
1/1 [==============================] - 0s 1ms/step - loss: 2.0119e-04
Epoch 3/10
1/1 [==============================] - 0s 1ms/step - loss: 2.0115e-04
Epoch 4/10
1/1 [==============================] - 0s 3ms/step - loss: 2.0114e-04
Epoch 5/10
1/1 [==============================] - 0s 2ms/step - loss: 2.0111e-04
Epoch 6/10
1/1 [==============================] - 0s 2ms/step - loss: 2.0107e-04
Epoch 7/10
1/1 [==============================] - 0s 2ms/step - loss: 2.0105e-04
Epoch 8/10
1/1 [==============================] - 0s 2ms/step - loss: 2.0102e-04
Epoch 9/10
1/1 [==============================] - 0s 2ms/step - loss: 2.0094e-04
Epoch 10/10
1/1 [==============================] - 0s 2ms/step - loss: 2.0077e-04


In [ ]:
# 모델 이용
model.predict(inV)

array([[40.00157 ],
       [41.99647 ],
       [43.991375],
       [45.98628 ],
       [47.98118 ],
       [49.97608 ]], dtype=float32)

In [ ]:
# 실제 데이터와 모델이 예측한 값 비교해보기
deV

판매량
0   40
1   42
2   44
3   46
4   48
5   50

In [ ]:
model.predict([[15]]) 

array([[30.027058]], dtype=float32)

In [ ]:
#보스턴 집값 예측하기

import tensorflow as tf
import pandas as pd

boston_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv';
boston_data = pd.read_csv(boston_path)
print(boston_data.columns)
print(boston_data.head())

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
      crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]


In [ ]:
#독립, 종속변수 분리하기
boston_inV = boston_data[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
boston_deV = boston_data[['medv']]
print(boston_inV.shape, boston_deV.shape)

(506, 13) (506, 1)


In [ ]:
X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

In [ ]:
model.fit(boston_inV, boston_deV, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 23.5059
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 23.1954
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 23.2104
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 22.9276
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 23.4811
Epoch 6/10
16/16 [==============================] - 0s 1000us/step - loss: 23.1423
Epoch 7/10
16/16 [==============================] - 0s 971us/step - loss: 23.4960
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 23.1558
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 23.3027
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 23.1180


In [ ]:
model.predict(boston_inV[5:10])

array([[25.791725 ],
       [22.663912 ],
       [19.607887 ],
       [11.4770565],
       [18.940313 ]], dtype=float32)

In [ ]:
boston_deV[5:10]

medv
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9

In [ ]:
model.get_weights()

[array([[-0.0967117 ],
        [ 0.04644271],
        [-0.00870267],
        [ 2.638686  ],
        [-6.4685526 ],
        [ 4.946126  ],
        [-0.00679091],
        [-1.1691504 ],
        [ 0.2259611 ],
        [-0.01017232],
        [-0.6238142 ],
        [ 0.01277576],
        [-0.47652832]], dtype=float32), array([15.152074], dtype=float32)]

In [ ]:
print(boston_inV['crim'])

0      0.00632
1      0.02731
2      0.02729
3      0.03237
4      0.06905
        ...   
501    0.06263
502    0.04527
503    0.06076
504    0.10959
505    0.04741
Name: crim, Length: 506, dtype: float64


In [ ]:
## 분류
import tensorflow as tf
import pandas as pd


In [ ]:
# 과거 데이터 준비
iris_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris_data = pd.read_csv(iris_path)
iris_data.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
#원핫인코딩/ 회귀가 아닌 분류, 분류를 위해 각 상태?를 숫자로
incoding_data = pd.get_dummies(iris_data)
incoding_data.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [ ]:
print(incoding_data.columns)
print(incoding_data.shape)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')
(150, 7)


In [ ]:
# 독립, 종속변수 
iris_inV = incoding_data[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
iris_deV = incoding_data[['품종_setosa', '품종_versicolor',
       '품종_virginica']]
print(iris_inV.shape, iris_deV.shape)

(150, 4) (150, 3)


In [ ]:
# 모델 구조 만들기
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

In [ ]:
# 모델 학습시키기
model.fit(iris_inV, iris_deV, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4118 - accuracy: 0.9533
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4112 - accuracy: 0.9200
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4103 - accuracy: 0.9467
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4090 - accuracy: 0.9533
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4084 - accuracy: 0.9400
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4075 - accuracy: 0.9533
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4065 - accuracy: 0.9400
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4054 - accuracy: 0.9467
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4044 - accuracy: 0.9533
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4040 - accuracy: 0.9467
Epoch 11/100
5/5 [===========

In [ ]:
model.predict(iris_inV[0:5])

array([[0.9782004 , 0.02048106, 0.00131862],
       [0.95196265, 0.04432873, 0.00370858],
       [0.9705312 , 0.0273879 , 0.00208091],
       [0.95141554, 0.04484359, 0.00374083],
       [0.98144126, 0.01747692, 0.00108185]], dtype=float32)

In [ ]:
print(iris_deV[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [ ]:
model.predict(iris_inV[-5:])

array([[0.00094311, 0.2740531 , 0.7250037 ],
       [0.00110132, 0.34118468, 0.657714  ],
       [0.0016529 , 0.360577  , 0.6377701 ],
       [0.00137229, 0.29683962, 0.7017881 ],
       [0.00278541, 0.41761082, 0.5796038 ]], dtype=float32)

In [ ]:
print(iris_deV[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [ ]:
# 학습한 가중치
model.get_weights()

[array([[ 0.36367607,  0.37840927,  0.28492627],
        [ 1.5400783 , -0.06445819, -0.5509237 ],
        [-1.5102527 ,  0.2597013 ,  0.43684742],
        [-1.3721509 , -0.426224  ,  0.97804004]], dtype=float32),
 array([ 1.3055042 ,  0.31290764, -0.7794716 ], dtype=float32)]

In [1]:
#히든레이어_ 보스턴 집값 예측
import tensorflow as tf
import pandas as pd

boston_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv';
boston_data = pd.read_csv(boston_path)
print(boston_data.columns)
print(boston_data.head())

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
      crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]


In [2]:
#독립, 종속변수 분리하기
boston_inV = boston_data[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
boston_deV = boston_data[['medv']]
print(boston_inV.shape, boston_deV.shape)

(506, 13) (506, 1)


In [4]:
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

In [8]:
#학습시키기
model.fit(boston_inV, boston_deV, epochs=1000, verbose=0)
model.fit(boston_inV, boston_deV, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 23.6193
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 23.5366
Epoch 3/10
16/16 [==============================] - 0s 987us/step - loss: 22.1780
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 23.9090
Epoch 5/10
16/16 [==============================] - 0s 993us/step - loss: 23.4116
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 23.4102
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 22.6165
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 25.8880
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 21.8341
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 24.4073


In [9]:
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [12]:
#모델 이용하기
print(model.predict(boston_inV[5:10]))
print(boston_deV[5:10])

[[23.875969]
 [20.207762]
 [16.921656]
 [ 8.341784]
 [16.346766]]
   medv
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9


In [13]:
##히든레이어, 아리리스 구분하기, 분류
import tensorflow as tf
import pandas as pd

# 과거 데이터 준비
iris_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris_data = pd.read_csv(iris_path)
iris_data.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [14]:
#원핫인코딩/ 회귀가 아닌 분류, 분류를 위해 각 상태?를 숫자로
incoding_data = pd.get_dummies(iris_data)
incoding_data.head()

print(incoding_data.columns)
print(incoding_data.shape)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')
(150, 7)


In [15]:
# 독립, 종속변수 
iris_inV = incoding_data[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
iris_deV = incoding_data[['품종_setosa', '품종_versicolor',
       '품종_virginica']]
print(iris_inV.shape, iris_deV.shape)

(150, 4) (150, 3)


In [16]:
# 모델 구조 만들기 
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish') (X)
H = tf.keras.layers.Dense(8, activation='swish') (H)
H = tf.keras.layers.Dense(8, activation='swish') (H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

In [ ]:
# 모델 학습시키기
model.fit(iris_inV, iris_deV, epochs=100)

In [19]:
# 모델 이용하기
print(model.predict(iris_inV[0:5]))
print(iris_deV[0:5])

[[9.86043572e-01 1.39308935e-02 2.55086325e-05]
 [9.82874632e-01 1.70805175e-02 4.49159234e-05]
 [9.83087957e-01 1.68645941e-02 4.74387489e-05]
 [9.82144475e-01 1.78031400e-02 5.23548588e-05]
 [9.85820055e-01 1.41533073e-02 2.66822899e-05]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [ ]:
model.weights

In [22]:
#성능 좋은 모델 이용한, 보스턴 집값 예측하기

import tensorflow as tf
import pandas as pd

boston_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv';
boston_data = pd.read_csv(boston_path)
print(boston_data.columns)
print(boston_data.head())



#독립, 종속변수 분리하기
boston_inV = boston_data[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
boston_deV = boston_data[['medv']]
print(boston_inV.shape, boston_deV.shape)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
      crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]
(506, 13) (506, 1)


In [23]:
# 성능좋은 모델 만들기 Batch
X = tf.keras.layers.Input(shape=[13])

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H) # Dense랑 activation사이에 
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

In [24]:
#학습시키기
model.fit(boston_inV, boston_deV, epochs=1000)

Epoch 1/1000
16/16 [==============================] - 0s 2ms/step - loss: 574.1701
Epoch 2/1000
16/16 [==============================] - 0s 1ms/step - loss: 565.8901
Epoch 3/1000
16/16 [==============================] - 0s 1ms/step - loss: 559.1821
Epoch 4/1000
16/16 [==============================] - 0s 2ms/step - loss: 552.2095
Epoch 5/1000
16/16 [==============================] - 0s 1ms/step - loss: 546.3000
Epoch 6/1000
16/16 [==============================] - 0s 1ms/step - loss: 539.9874
Epoch 7/1000
16/16 [==============================] - 0s 1ms/step - loss: 533.0714
Epoch 8/1000
16/16 [==============================] - 0s 2ms/step - loss: 527.9516
Epoch 9/1000
16/16 [==============================] - 0s 1ms/step - loss: 521.2584
Epoch 10/1000
16/16 [==============================] - 0s 1ms/step - loss: 515.2341
Epoch 11/1000
16/16 [==============================] - 0s 1ms/step - loss: 509.0255
Epoch 12/1000
16/16 [==============================] - 0s 1ms/step - loss: 501.9034
E

In [29]:
model.fit(boston_inV, boston_deV, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 7.5240
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 8.2636
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 9.1438
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 7.8581
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 10.2199
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 9.6634
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 8.9490
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 10.2473
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 12.0141
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 9.0809
